# Generated by Django 5.1 on 2025-04-08 11:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='emails',
            name='email_group',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app.emailgroup'),
            preserve_default=False,
        ),
    ]
