# Generated by Django 5.1 on 2025-04-08 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_emails_email_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emails',
            name='email',
            field=models.TextField(),
        ),
    ]
